#CREATE TABLE SALES 
#(
#	PURCHASE_NUMBER INT NOT NULL PRIMARY KEY AUTO_INCREMENT , #AUTO INCREMENT GOES WITH PRIMARY,UNIQUE , INDEX KEY
 #   DATE_OF_PURCHASE DATE NOT NULL,
  #  CUSTOMER_ID INT,
   # ITEM_CODE VARCHAR(10) NOT NULL
#);

#TO DROP TABLE
#DROP TABLE SALES;
#DROP TABLE CUSTOMERS;
#DROP TABLE ITEMS;
DROP TABLE COMPANIES;
CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    NUMBER_OF_COMPLAINTS INT,
    primary key (CUSTOMER_ID)
);

CREATE TABLE ITEMS 
(
	ITEM_ID VARCHAR(255),
    ITEM VARCHAR(255),
    UNIT_PRICE NUMERIC(10,2),
    COMPANY_ID VARCHAR(255),
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE COMPANIES
(
	COMPANY_ID VARCHAR(255),
    COMPANY_NAME VARCHAR(255),
    HEADQUATERS_PHONE_NUMBER INT(12),
    PRIMARY KEY (COMPANY_ID)
);
