CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID INT NOT NULL PRIMARY KEY auto_increment,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    NUMBER_OF_COMPLAINTS INT 
    
);

#ALTER STATEMENTS

ALTER TABLE CUSTOMERS

ADD COLUMN GENDER ENUM('M','F') AFTER LAST_NAME ;

INSERT INTO CUSTOMERS (FIRST_NAME,LAST_NAME,GENDER,EMAIL_ADDRESS,NUMBER_OF_COMPLAINTS)
VALUES('SHIPRA','CHAUHAN','F','777CHAUHANSHIPRA@GMAILO.COM',1);

ALTER TABLE CUSTOMERS
CHANGE COLUMN NUMBER_OF_COMPLAINTS NUMBER_OF_COMPLAINTS INT DEFAULT 0;

SELECT * FROM CUSTOMERS;

#DROPPING DEAFULT 
ALTER TABLE CUSTOMERS
ALTER COLUMN NUMBER_OF_COMPLAINTS DROP DEFAULT;

CREATE TABLE COMPANIES
(
	COMPANY_ID VARCHAR(255),
    COMPANY_NAME VARCHAR(255) default 'X' ,
    HEADQUATERS_PHONE_NUMBER INT(12)
);

ALTER TABLE COMPANIES
ADD UNIQUE KEY (HEADQUATERS_PHONE_NUMBER);

#MODIFYING NOTNULL CONSTRAINT TO NULL

ALTER TABLE CUSTOMERS
MODIFY CUSTOMER_ID INT NULL; #REMOVING NOT NULL

ALTER TABLE CUSTOMERS
CHANGE COLUMN CUSTOMER_ID CUSTOMER_ID INT NOT NULL ; # ADDING NOT NULL CONSTRAINT 


