
CREATE TABLE SALES 
(
	PURCHASE_NUMBER INT ,
    DATE_OF_PURCHASE DATE,
    CUSTOMER_ID INT,
    ITEM_CODE VARCHAR(10),
    PRIMARY KEY (CUSTOMER_ID)
    #ADDIND FOREIGN KEY 
	#FOREIGN KEY (CUSTOMER_ID) references CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE 
);

#FOREIGN KEY CAN ALSO BE ADDED TO AN EXISITING TABLE 

#ALTER TABLE SALES 
#ADD FOREIGN KEY (CUSTOMER_ID) REFRENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE 

ALTER TABLE SALES
ADD UNIQUE KEY (ITEM_CODE);

#DROPPING UNIQUE KEY

ALTER TABLE SALES
DROP INDEX ITEM_CODE; #DON'T USE PARENTHESIS WHILE DROPPING UNIQUE KEY

