# WILD CARD OPERATORS
#% _ *

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE ("%JACK%");

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME NOT LIKE ("%JACK%");

# BETWEEN - AND / NOT BETWEEN - AND 
# FOR VALUES IN BETWEEN AND OPPOSITE 


SELECT * FROM salaries
WHERE SALARY BETWEEN 66000 AND 70000;

SELECT * FROM employees
WHERE EMP_NO NOT BETWEEN "10004" AND "10012";

SELECT * FROM departments
WHERE DEPT_NO BETWEEN "D003" AND "D006";


