SELECT EMP_NO  
FROM DEPT_EMP 
WHERE FROM_DATE >"2000-01-01"
GROUP BY EMP_NO
HAVING COUNT(FROM_DATE)>1
ORDER BY EMP_NO ASC;

#LIMIT 
/* TO CHANGE DEFAULT LIMIT 
EDIT>PREFERENCES>SQLEDITOR>SQL EXECUTION>LIMIT COUNT

*/
SELECT * FROM DEPT_EMP LIMIT 100; 